services:
  foodie:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel57-app
    container_name: foodie
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: foodie-db
    environment:
      MYSQL_DATABASE: local
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: foodie-phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"

volumes:
  dbdata:
